name: CMD
api:  3.8.1
version: 1.0.0
main: David\CMD\Main
author: David
load: STARTUP
commands:
  Day:
    description: §bMake Day.
    usage: "/tag"
    permission: time.command
  Night:
    description: §bMake Night.
    usage: "/nacht"
    permission: time.command
  gm0:
    description: §cSet you in gm0
    usage: "/gm0"
    permission: gamemode.command
  gm2:
    description: §cSet you in gm2
    usage: "/gm2"
    permission: gamemode.command
  gm1:
    description: §cSet you in gm1
    usage: "/gm1"
    permission: gamemode.command
  gm3:
    description: §cSet you in gm3
    usage: "/gm3"
    permission: gamemode.command
  heal:
    description: §6Fill your Healt.
    usage: "/heal"
    permission: heal.command
  food:
    description: §6Fill your Hunger.
    usage: "/food"
    permission: food.command
