name: CMD
api: 3.8.1
version: 1.0.0
main: David\CMD\Main
author: David
load: STARTUP
commands:
tag:
description:
usage: "/tag"
permission: time.cmd
nacht:
description: Macht Nacht
usage: "/nacht"
permision: time.cmd
gm0:
description: §cSetzt dich in den gm0
usage: "/gm0"
permission: gm.cmd
gm2:
description:
usage: "/gm2"
permission: gm.cmd
gm1:
description: §4Du bist Jetzt in GM1
usage: "/gm1"
permission: gm.cmd
gm3:
description: §4Du bist Jetzt in GM3
usage: "/GM3"
permission: gm.cmd
Heal:
description: §4Du wurdest Geheilt.
usage: "/Heal"
food:
description: §4Du Hast Jetzt Kein hunger mehr.
usage: "/food"
permission: food.cmd

